[[dialog]]
character = "raptor"
font_family = "default"
font_size = 15

[[dialog]]
character = "help-sign"
font_family = "default"
font_size = 20

[[dialog]]
character = "raptor-lady"
font_family = "default"
font_size = 15
