[1]
speaker = "raptor-lady"
expression = "Afraid"
name = "Trapped Dinosaur"
text = "You, Mr. Raptor. Please, I am trapped, help me!"

    [1.1]
    evil_requirement = 10
    name = "Mr. Raptor"
    expression = "Angry"
    key = "help_dinosaur_1"
    value = "evil"
    speaker = "raptor"
	button = "Uh, excuse me?"
    text = "It's Emperor RAPTR. Get yourself out."

        [1.1.1]
        name = "Likely Dead Dinosaur"
        expression = "Afraid"
        speaker = "raptor-lady"
        text = "No, wait. I am sorry! Emperor, sir, help me!"

            [1.1.1.1]
            name = "Emperor RAPTR"
            expression = "Angry"
            speaker = "raptor"
            text = "lol, bye."

    [1.2]
    name = "Raptr"
    expression = "Happy"
    key = "help_dinosaur_1"
    value = "wholesome"
    speaker = "raptor"
	button = "What happened?!"
    text = "Of course! Let me give you a hand."
    trigger = "save_dinosaur_1"

        [1.2.1]
        name = "Trapped Dinosaur"
        expression = "Happy"
        speaker = "raptor-lady"
        text = "Thank goodness. Those humans put me here."

            [1.2.1.1]
            name = "Raptr"
            expression = "Happy"
            evil_requirement = 1
            key = "hate_humans_1"
            speaker = "raptor"
            value = "evil"
			button = "(push stomach out and pat on its sides)"
            text = "Don't worry, I ate like 20 on my way here, so even?"

                [1.2.1.1.1]
                name = "Seductively Trapped Dinosaur"
                expression = "Happy"
                speaker = "raptor-lady"
                text = "That's actually kind of hot."

            [1.2.1.2]
            name = "Raptr"
            expression = "Sad"
            speaker = "raptor"
            key = "hate_humans_1"
            value = "wholesome"
			button = "(show a sense of sadness and confusion)"
            text = "They don't understand us yet."

                [1.2.1.2.1]
                name = "Trapped Dinosaur"
                expression = "Angry"
                speaker = "raptor-lady"
                text = "Hmph."
