# This module defines:
#
#  SDL2_TTF_INCLUDE_DIR
#  SDL2_TTF_LIBRARY
#  SDL2_TTF_FOUND
#

FIND_PATH(SDL2_TTF_INCLUDE_DIR NAMES SDL_ttf.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)

if(SDL2_TTF_FOUND AND NOT TARGET sdl2_ttf::sdl2_ttf)
    add_library(sdl2_ttf::sdl2_ttf INTERFACE IMPORTED)
    set_target_properties(sdl2_ttf::sdl2_ttf PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${SDL2_TTF_INCLUDE_DIR}"
	INTERFACE_LINK_LIBRARIES "${SDL2_TTF_LIBRARY}"
    )
endif()
