# This module defines:
#
#  SDL2_NET_INCLUDE_DIR
#  SDL2_NET_LIBRARY
#  SDL2_NET_FOUND
#

FIND_PATH(SDL2_NET_INCLUDE_DIR NAMES SDL_net.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_NET_LIBRARY NAMES SDL2_net)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(sdl2_net REQUIRED_VARS SDL2_NET_LIBRARY SDL2_NET_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_NET_INCLUDE_DIR SDL2_NET_LIBRARY)

if(SDL2_NET_FOUND AND NOT TARGET sdl2_net::sdl2_net)
    add_library(sdl2_net::sdl2_net INTERFACE IMPORTED)
    set_target_properties(sdl2_net::sdl2_net PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${SDL2_NET_INCLUDE_DIR}"
	INTERFACE_LINK_LIBRARIES "${SDL2_NET_LIBRARY}"
    )
endif()
